#!/usr/bin/env node
import fs from 'node:fs'; import path from 'node:path';
import { readJson, writeText } from './lib/files.mjs';
function mapArgs(argv){const m={};for(let i=0;i<argv.length;i++){if(argv[i].startsWith('--')){const k=argv[i].slice(2);m[k]=argv[i+1]&&!argv[i+1].startsWith('--')?argv[++i]:true;}}return m;}
function bullets(v){if(!v)return '- 待补充';if(Array.isArray(v))return v.map(x=>`- ${typeof x==='string'?x:JSON.stringify(x)}`).join('\n');return String(v);}
function replaceAll(t, vars){return t.replace(/\{\{([a-zA-Z0-9_]+)\}\}/g,(_,k)=>vars[k]??'待补充');}
const a=mapArgs(process.argv.slice(2));if(!a.event||!a.type||!a.out){console.error('Usage: render_draft.mjs --event event.json --type experiment|adr|status|knowledge-note|learning-path --out draft.md');process.exit(2);}
const e=readJson(a.event);const file={'experiment':'experiment.md','adr':'adr.md','status':'project-status.md','knowledge-note':'knowledge-note.md','learning-path':'learning-path.md'}[a.type];if(!file)throw new Error('Unsupported type');
const template=fs.readFileSync(path.join(path.dirname(new URL(import.meta.url).pathname),'../assets/templates',file),'utf8');
const d=e.details||{}; const evidence=(e.evidence||[]).map(x=>`${x.title}: ${x.source}`).join('; ');
const vars={title:d.title||e.summary,date:(e.occurred_at||new Date().toISOString()).slice(0,10),status:d.status||'Draft',environment:d.environment||'待补充',sources:evidence||'待补充',goal:d.goal||e.summary,hypothesis:d.hypothesis||'待补充',steps:bullets(d.steps),observations:bullets(d.observations),conclusion:d.conclusion||'待确认',limitations:bullets(d.limitations),next:bullets(d.next),number:d.number||'待编号',decision_makers:d.decision_makers||'待确认',context:d.context||e.summary,drivers:bullets(d.drivers),options:bullets(d.options),decision:d.decision||'待确认',consequences:bullets(d.consequences),risks:bullets(d.risks),phase:d.phase||'待确认',objective:d.objective||e.summary,updated_at:new Date().toISOString(),evidence_summary:evidence||'待补充',completed:bullets(d.completed),in_progress:bullets(d.in_progress),blockers:bullets(d.blockers),evidence:bullets(e.evidence),knowledge_type:d.knowledge_type||'待分类',domain:d.domain||'待分类',summary:e.summary,content:d.content||'待补充',scope:d.scope||'待补充',relations:bullets(d.relations),unknowns:bullets(d.unknowns),baseline:d.baseline||'待确认',time_budget:d.time_budget||'待确认',duration:d.duration||'待确认',deliverable:d.deliverable||'待确认',stages:bullets(d.stages),acceptance:bullets(d.acceptance),optional:bullets(d.optional)};
writeText(a.out,replaceAll(template,vars));console.log(`Draft written: ${a.out}`);
