#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";
import { run, parseJsonLoose } from "./lib/cli.mjs";
import { assertRelative } from "./lib/files.mjs";
function args(argv){const [command,...rest]=argv,m={command};for(let i=0;i<rest.length;i++)if(rest[i].startsWith("--")){const k=rest[i].slice(2);m[k]=rest[i+1]&&!rest[i+1].startsWith("--")?rest[++i]:true;}return m;}
function images(content,file){const out=[],re=/!\[([^\]]+)\]\(([^)]+)\)/g;let m;while((m=re.exec(content))){const ref=m[2].trim();if(/^https?:\/\//i.test(ref)||ref.startsWith("asset://")||path.isAbsolute(ref)||ref.split(/[\\/]+/).includes(".."))throw new Error(`Image must be document-local: ${ref}`);if(!ref.startsWith("./assets/"))throw new Error(`Image must be under ./assets/: ${ref}`);const full=path.resolve(path.dirname(file),ref);if(!fs.existsSync(full))throw new Error(`Image missing: ${ref}`);const before=content.slice(0,m.index).split("\n");let anchor=null;for(let i=before.length-1;i>=0;i--){const h=before[i].match(/^#{2,3}\s+(.+)$/);if(h){anchor=h[1].trim();break;}}if(!anchor)throw new Error(`Image requires a preceding H2/H3 anchor: ${ref}`);const after=content.slice(m.index+m[0].length,m.index+m[0].length+500);if(!/^\s*\n\s*### AI 可读语义镜像/m.test(after))throw new Error(`Image lacks AI-readable semantic mirror: ${ref}`);out.push({alt:m[1],ref,full,anchor,raw:m[0]});}return out;}
function strip(content,refs){let out=content;for(const r of refs)out=out.replace(r.raw+"\n","");return out;}
const a=args(process.argv.slice(2));if(!["create","overwrite","append"].includes(a.command)||!a.content){console.error("Usage: lark_write.mjs create|overwrite|append --content relative.md ...");process.exit(2);}assertRelative(a.content);if(!fs.existsSync(a.content))throw new Error(`Content file not found: ${a.content}`);const applying=Boolean(a.apply);if(applying&&a.confirm!=="I_APPROVE_FEISHU_WRITE")throw new Error("Real write requires --confirm I_APPROVE_FEISHU_WRITE");const identity=a.identity||"user",content=fs.readFileSync(a.content,"utf8"),refs=images(content,a.content);const tmp=refs.length?`.tmp_feishu_text_${process.pid}.md`:null;if(tmp)fs.writeFileSync(tmp,strip(content,refs));const argv=["docs"];if(a.command==="create"){if(!a["parent-token"])throw new Error("--parent-token required");argv.push("+create","--content",`@${tmp||a.content}`,"--parent-token",a["parent-token"]);}else{if(!a.doc)throw new Error("--doc required");argv.push("+update","--doc",a.doc,"--command",a.command,"--content",`@${tmp||a.content}`);}argv.push("--as",identity,"--format","json");if(!applying)argv.push("--dry-run");const text=run("lark-cli",argv,{allowFailure:true});if(tmp&&fs.existsSync(tmp))fs.unlinkSync(tmp);if(text.status===10){console.error(text.stderr||text.stdout);console.error("Confirmation gate detected; do not bypass it.");process.exit(10);}if(text.status!==0){console.error(text.stderr||text.stdout);process.exit(text.status);}let output;try{output=parseJsonLoose(text.stdout);}catch{output=text.stdout;}console.log(JSON.stringify(output,null,2));if(!applying||!refs.length)process.exit(0);const doc=a.doc||output?.data?.document?.document_id;if(!doc)throw new Error("Cannot determine Feishu document token for media insertion");for(const r of refs){const cmd=["docs","+media-insert","--doc",doc,"--file",r.full,"--type","image","--selection-with-ellipsis",r.anchor,"--width","1200","--as",identity,"--format","json"];const res=run("lark-cli",cmd,{allowFailure:true});if(res.status!==0)throw new Error(`Media insert failed for ${r.ref}: ${res.stderr||res.stdout}`);console.error(`Inserted ${r.ref} after ${r.anchor}`);}
