export const CONTRACT_VERSION = "0.1.0";
export const GATEWAY_ENVELOPE_VERSION = "1.0";

export const APPLICATION_OPERATIONS = Object.freeze({
  HOST_REGISTER: "browser.host.register",
  HOST_HEARTBEAT: "browser.host.heartbeat",
  DISPATCH_LIST_PENDING: "browser.dispatch.listPending",
  DISPATCH_CLAIM: "browser.dispatch.claim",
  DISPATCH_GET: "browser.dispatch.get",
  DISPATCH_DELIVERY_ACK: "browser.dispatch.deliveryAck",
  DISPATCH_HOST_RESULT: "browser.dispatch.hostResult",
  DISPATCH_UNCERTAIN: "browser.dispatch.uncertain",
  DISPATCH_FAIL: "browser.dispatch.fail",
  DISPATCH_ACK_LEGACY: "browser.dispatch.ack",
  DISPATCH_REPORT_LEGACY: "browser.dispatch.report",
  PAYLOAD_RESOLVE: "browser.payload.resolve",
  APPROVAL_GRANT_GET: "approval.grant.get",
  APPROVAL_GRANT_CONSUME: "approval.grant.consume"
});

export const ACTION_TYPES = Object.freeze({
  OBSERVE_PAGE: "OBSERVE_PAGE",
  FOLLOW_LATEST: "FOLLOW_LATEST",
  OPEN_OR_RESUME_SESSION: "OPEN_OR_RESUME_SESSION",
  CONTINUE_ROLE_SESSION: "CONTINUE_ROLE_SESSION",
  SET_COMPOSER_TEXT: "SET_COMPOSER_TEXT",
  SUBMIT_MESSAGE: "SUBMIT_MESSAGE",
  STOP_GENERATION: "STOP_GENERATION",
  CLICK_REGISTERED_UI: "CLICK_REGISTERED_UI",
  WAIT_FOR_RESPONSE: "WAIT_FOR_RESPONSE"
});

export const HIGH_RISK_ACTIONS = new Set([
  ACTION_TYPES.OPEN_OR_RESUME_SESSION,
  ACTION_TYPES.CONTINUE_ROLE_SESSION,
  ACTION_TYPES.SET_COMPOSER_TEXT,
  ACTION_TYPES.SUBMIT_MESSAGE,
  ACTION_TYPES.STOP_GENERATION,
  ACTION_TYPES.CLICK_REGISTERED_UI
]);

export const PLATFORM_WAKE_ACTIONS = new Set([
  ACTION_TYPES.OPEN_OR_RESUME_SESSION,
  ACTION_TYPES.CONTINUE_ROLE_SESSION,
  ACTION_TYPES.SUBMIT_MESSAGE
]);

export const APPROVAL_POLICY_MODE = Object.freeze({
  STRICT: "strict",
  PLATFORM_WAKE_CANDIDATE: "platform_wake_candidate",
  // Kept as an input alias for configs written by the first remediation.
  PLATFORM_WAKE_PROPOSAL: "platform_wake_proposal"
});

export const HOST_RESULT_STATUS = Object.freeze({
  DELIVERED: "DELIVERED",
  ACTION_SUCCEEDED: "ACTION_SUCCEEDED",
  ACTION_FAILED: "ACTION_FAILED",
  UNCERTAIN: "UNCERTAIN",
  BLOCKED: "BLOCKED",
  EXPIRED: "EXPIRED",
  CANCELLED: "CANCELLED"
});

export const JOURNAL_STATE = Object.freeze({
  RECEIVED: "RECEIVED",
  CLAIMED: "CLAIMED",
  PREPARED: "PREPARED",
  EXECUTING: "EXECUTING",
  PRE_DELIVERY_FAILURE_PENDING: "PRE_DELIVERY_FAILURE_PENDING",
  DELIVERY_ACK_PENDING: "DELIVERY_ACK_PENDING",
  DELIVERY_CONFIRMED: "DELIVERY_CONFIRMED",
  DELIVERY_ACKED: "DELIVERY_ACKED",
  HOST_RESULT_PENDING: "HOST_RESULT_PENDING",
  EXECUTED: "EXECUTED",
  REPORTED: "REPORTED",
  FAILED: "FAILED",
  UNCERTAIN: "UNCERTAIN",
  QUARANTINED: "QUARANTINED",
  // Legacy names are retained only for migration of already persisted MVP journals.
  PRECHECKED: "PRECHECKED",
  SIDE_EFFECT_STARTED: "SIDE_EFFECT_STARTED",
  SIDE_EFFECT_CONFIRMED: "SIDE_EFFECT_CONFIRMED"
});

export const BINDING_STATE = Object.freeze({
  PROVISIONING: "PROVISIONING",
  READY: "READY",
  STALE: "STALE",
  PAUSED: "PAUSED",
  BLOCKED: "BLOCKED"
});

export const ASSESSMENT_DECISIONS = new Set([
  "NO_ACTION",
  "REQUEST_MORE_OBSERVATION",
  "ESCALATE_TO_CONTROLLER",
  "REQUEST_HUMAN_REVIEW"
]);
